# Generated by Django 3.1 on 2020-08-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNoteMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_pk', models.PositiveIntegerField()),
                ('note_description', models.TextField(blank=True, null=True)),
                ('created_at', models.PositiveIntegerField()),
                ('updated_at', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('amount_paid', models.PositiveIntegerField()),
                ('amount_due', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('receipt', models.CharField(blank=True, max_length=255, null=True)),
                ('offer_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.PositiveIntegerField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.PositiveIntegerField()),
                ('updated_at', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
