# Generated by Django 3.1 on 2020-08-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpay', '0002_auto_20200812_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(max_length=255),
        ),
    ]
