# Generated by Django 3.1 on 2020-08-20 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('razorpay', '0004_auto_20200812_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, max_length=255)),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_international', models.BooleanField(default=False)),
                ('method', models.CharField(max_length=25)),
                ('amount_refunded', models.PositiveIntegerField(default=0)),
                ('refund_status', models.PositiveIntegerField(blank=True, choices=[(0, 'Initiated'), (1, 'Processing'), (2, 'Refunded'), (3, 'Cancelled')], null=True)),
                ('captured', models.PositiveIntegerField(default=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('wallet_id', models.PositiveIntegerField(blank=True, null=True)),
                ('card_id', models.CharField(blank=True, max_length=255, null=True)),
                ('vpa', models.CharField(blank=True, max_length=255, null=True)),
                ('fee', models.PositiveIntegerField(blank=True, null=True)),
                ('tax', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('merchant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_key', models.CharField(blank=True, max_length=255, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wallet',
            },
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Created'), (1, 'Authorized'), (2, 'Captured'), (3, 'Refunded'), (4, 'Failed')], null=True),
        ),
    ]
